title: dashingDev
email: ideas for developing code & yourself
description: >-
  dashingDev is a card deck designed to inspire, improve and remind developers.
  Each card summarizes a core concept in software development.
  The deck is for people from all kinds of backgrounds and all levels of skill.
  The cards are not specific to any technology – they describe the fundamentals of software design & development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  cards:
    output: true

host: 0.0.0.0
livereload: true
